osakanas = [
  {
    "Fish": "トラマフィッシュ",
    "Spot": "オークウッド",
    "Zone": "高地ラノシア",
    "From": 17,
    "To": 20,
    "Previous_Weather": "",
    "Weather": "曇り・霧",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "スピナーベイト",
    "Mooch": "スカルピン",
    "Hookset": "",
    "Neko": 241,
    "Since": 2.3,
    "Remark": ""
  },
  {
    "Fish": "スウィートニュート",
    "Spot": "ラベンダーベッド",
    "Zone": "ラベンダーベッド",
    "From": 23,
    "To": 4,
    "Previous_Weather": "",
    "Weather": "霧",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "コスリカ",
    "Mooch": "グラディエーターベタ",
    "Hookset": "",
    "Neko": 259,
    "Since": 2.3,
    "Remark": ""
  },
  {
    "Fish": "リトルペリュコス",
    "Spot": "常夏の島北",
    "Zone": "東ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雨・暴雨",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ラグワーム",
    "Mooch": "メルトールゴビー→ワフー",
    "Hookset": "",
    "Neko": 637,
    "Since": 4,
    "Remark": "no ヌシヒット"
  },
  {
    "Fish": "ファットパース",
    "Spot": "リバーズミート",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 462,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "ヘイルイーター",
    "Spot": "グレイテール滝",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "雪・吹雪",
    "Weather": "吹雪",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ジャンボガンボボ",
    "Mooch": "グレイシャーコア",
    "Hookset": "プレシジョン",
    "Neko": 478,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "フレアフィッシュ",
    "Spot": "クルザス不凍池",
    "Zone": "クルザス西部高地",
    "From": 10,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "吹雪",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ツチグモ",
    "Mooch": "ハルオネ",
    "Hookset": "ストロング",
    "Neko": 479,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "ラ・レアル",
    "Spot": "アッシュプール",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 464,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "イエティキラー",
    "Spot": "ドラゴンスピット",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 463,
    "Since": 3.3,
    "Remark": "引っ掛け 50s+"
  },
  {
    "Fish": "氷の巫女",
    "Spot": "ベーンプール西",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "雪",
    "Weather": "吹雪",
    "Fish_Eyes": "2m20s",
    "Intuition": "",
    "Bait": "カディスラーヴァ",
    "Mooch": "ハルオネ",
    "Hookset": "ストロング",
    "Neko": 488,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "ネモ",
    "Spot": "ベーンプール南",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "雪",
    "Weather": "吹雪",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 490,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "ビショップフィッシュ",
    "Spot": "クリアプール",
    "Zone": "クルザス西部高地",
    "From": 10,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Fish_Eyes": "3m",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 489,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "シャリベネ",
    "Spot": "クリアプール",
    "Zone": "クルザス西部高地",
    "From": 0,
    "To": 3,
    "Previous_Weather": "",
    "Weather": "吹雪",
    "Fish_Eyes": "",
    "Intuition": "ハルオネx5",
    "Bait": "ツチグモ",
    "Mooch": "ハルオネ",
    "Hookset": "プレシジョン",
    "Neko": 504,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "アクムノタネ",
    "Spot": "スモーキングウェイスト",
    "Zone": "高地ドラヴァニア",
    "From": 22,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "曇り・霧・砂塵",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 466,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "スケイルリッパー",
    "Spot": "悲嘆の飛泉",
    "Zone": "高地ドラヴァニア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "曇り・霧・砂塵",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 465,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "フォークタン",
    "Spot": "ウィロームリバー",
    "Zone": "高地ドラヴァニア",
    "From": 12,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 480,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "サンダースケイル",
    "Spot": "飽食の台地",
    "Zone": "高地ドラヴァニア",
    "From": 6,
    "To": 8,
    "Previous_Weather": "曇り・霧・砂塵",
    "Weather": "雷",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ストーンラーヴァ",
    "Mooch": "マクロブラキウム",
    "Hookset": "ストロング",
    "Neko": 494,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "リドル",
    "Spot": "アネス・ソー",
    "Zone": "高地ドラヴァニア",
    "From": 8,
    "To": 16,
    "Previous_Weather": "快晴",
    "Weather": "快晴",
    "Fish_Eyes": "5m",
    "Intuition": "",
    "Bait": "マグマワーム",
    "Mooch": "グラナイトクラブ",
    "Hookset": "ストロング",
    "Neko": 495,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "メテオトータス",
    "Spot": "モーン大岩窟",
    "Zone": "高地ドラヴァニア",
    "From": 8,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "マグマワーム",
    "Mooch": "グラナイトクラブ",
    "Hookset": "ストロング",
    "Neko": 467,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "聖竜の涙",
    "Spot": "モーン大岩窟西",
    "Zone": "高地ドラヴァニア",
    "From": 2,
    "To": 6,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "2m+ 2択ガチャ（2m→1mはハズレ）",
    "Intuition": "",
    "Bait": "マグマワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 484,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "溶岩帝王",
    "Spot": "光輪の祭壇",
    "Zone": "高地ドラヴァニア",
    "From": 8,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Fish_Eyes": "5m (3択ガチャ)",
    "Intuition": "",
    "Bait": "マグマワーム",
    "Mooch": "グラナイトクラブ",
    "Hookset": "ストロング",
    "Neko": 496,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "プロブレマティカス",
    "Spot": "光輪の祭壇",
    "Zone": "高地ドラヴァニア",
    "From": 10,
    "To": 15,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Fish_Eyes": "3m (アロワナ)",
    "Intuition": "アロワナx3 カニx5",
    "Bait": "マグマワーム",
    "Mooch": "グラナイトクラブ",
    "Hookset": "ストロング",
    "Neko": 500,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "水瓶王",
    "Spot": "サリャク河",
    "Zone": "低地ドラヴァニア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブレーデッドジグ",
    "Mooch": "香魚",
    "Hookset": "ストロング",
    "Neko": 468,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "マダムバタフライ",
    "Spot": "クイックスピル・デルタ",
    "Zone": "低地ドラヴァニア",
    "From": 21,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ストーンラーヴァ",
    "Mooch": "グリルダロパ",
    "Hookset": "プレシジョン",
    "Neko": 481,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "万能のゴブリバス",
    "Spot": "サリャク河中州",
    "Zone": "低地ドラヴァニア",
    "From": 2,
    "To": 6,
    "Previous_Weather": "雨",
    "Weather": "暴雨",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブレーデッドジグ",
    "Mooch": "香魚",
    "Hookset": "ストロング",
    "Neko": 487,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "スピーカー",
    "Spot": "サリャク河上流",
    "Zone": "低地ドラヴァニア",
    "From": "",
    "To": "",
    "Previous_Weather": "曇り・霧",
    "Weather": "暴雨",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ツチグモ",
    "Mooch": "グリルダロパ",
    "Hookset": "ストロング",
    "Neko": 497,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "鎧魚",
    "Spot": "サリャク河上流",
    "Zone": "低地ドラヴァニア",
    "From": 1,
    "To": 4,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ツチグモ",
    "Mooch": "グリルダロパ",
    "Hookset": "プレシジョン",
    "Neko": 502,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "ハイアラガンクラブ改",
    "Spot": "アルファ管区",
    "Zone": "アジス・ラー",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "バイオレットワーム",
    "Mooch": "白金魚",
    "Hookset": "ストロング",
    "Neko": 473,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "魔科学物質666",
    "Spot": "廃液溜まり",
    "Zone": "アジス・ラー",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "有",
    "Intuition": "",
    "Bait": "バイオレットワーム",
    "Mooch": "白金魚",
    "Hookset": "プレシジョン",
    "Neko": 485,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "セティ",
    "Spot": "超星間交信塔",
    "Zone": "アジス・ラー",
    "From": 18,
    "To": 22,
    "Previous_Weather": "曇り",
    "Weather": "雷",
    "Fish_Eyes": "3m",
    "Intuition": "",
    "Bait": "バイオレットワーム",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 492,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "バイオガピラルク",
    "Spot": "デルタ管区",
    "Zone": "アジス・ラー",
    "From": 21,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "曇り",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ツチグモ",
    "Mooch": "エーテルアイ",
    "Hookset": "ストロング",
    "Neko": 474,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "ハンドレッドアイ",
    "Spot": "パプスの大樹",
    "Zone": "アジス・ラー",
    "From": 6,
    "To": 10,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ツチグモ",
    "Mooch": "エーテルアイ",
    "Hookset": "プレシジョン",
    "Neko": 486,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "クリスタルピジョン",
    "Spot": "ハビスフィア",
    "Zone": "アジス・ラー",
    "From": "",
    "To": "",
    "Previous_Weather": "晴れ",
    "Weather": "雷",
    "Fish_Eyes": "3m",
    "Intuition": "",
    "Bait": "ジャンボガガンボ",
    "Mooch": "スカイハイフィッシュ",
    "Hookset": "ストロング",
    "Neko": 493,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "アラガンブレード・シャーク",
    "Spot": "アジス・ラー旗艦島",
    "Zone": "アジス・ラー",
    "From": "",
    "To": "",
    "Previous_Weather": "曇り",
    "Weather": "雷",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "バイオレットワーム",
    "Mooch": "白金魚",
    "Hookset": "ストロング",
    "Neko": 477,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "オパビニア",
    "Spot": "アジス・ラー旗艦島",
    "Zone": "アジス・ラー",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷",
    "Fish_Eyes": "2m (オプロプケン)",
    "Intuition": "2m/オプロプケン3匹",
    "Bait": "バイオレットワーム",
    "Mooch": "白金魚",
    "Hookset": "プレシジョン",
    "Neko": 501,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "ザ・セカンドワン",
    "Spot": "ブルーウィンドウ",
    "Zone": "アバラシア雲海",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "風",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ジャンボガガンボ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 472,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "シーロストラタスモトロ",
    "Spot": "クラウドトップ",
    "Zone": "アバラシア雲海",
    "From": 10,
    "To": 13,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ジャンボガガンボ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 483,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "クラウドバタフライ",
    "Spot": "モック・ウーグル島",
    "Zone": "アバラシア雲海",
    "From": 5,
    "To": 7,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ジャンボガガンボ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 503,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "バスキングシャーク",
    "Spot": "モック・ウーグル島",
    "Zone": "アバラシア雲海",
    "From": "",
    "To": "",
    "Previous_Weather": "霧",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "レッドバルーン",
    "Mooch": "スカイフェアリー・セレネ",
    "Hookset": "ストロング",
    "Neko": 476,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "パイッサキラー",
    "Spot": "雲溜まり",
    "Zone": "アバラシア雲海",
    "From": 8,
    "To": 12,
    "Previous_Weather": "霧",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブレーデッドジグ",
    "Mooch": "ブルフロッグ",
    "Hookset": "ストロング",
    "Neko": 491,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "水墨魚",
    "Spot": "ヴール・シアンシラン",
    "Zone": "アバラシア雲海",
    "From": 14,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Fish_Eyes": "有",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 471,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "ラタトスクソウル",
    "Spot": "ランドロード遺構",
    "Zone": "ドラヴァニア雲海",
    "From": 4,
    "To": 6,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ジャンボガガンボ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 470,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "ヴィゾーヴニル",
    "Spot": "エイル・トーム",
    "Zone": "ドラヴァニア雲海",
    "From": 8,
    "To": 10,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 469,
    "Since": 3.3,
    "Remark": ""
  },
  {
    "Fish": "ディモルフォドン",
    "Spot": "ソーム・アル笠雲",
    "Zone": "ドラヴァニア雲海",
    "From": "",
    "To": "",
    "Previous_Weather": "快晴",
    "Weather": "暴風",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ジャンボガガンボ",
    "Mooch": "スカイハイフィッシュ",
    "Hookset": "ストロング",
    "Neko": 475,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "モグルグポンポン",
    "Spot": "グリーンスウォード島",
    "Zone": "ドラヴァニア雲海",
    "From": 10,
    "To": 13,
    "Previous_Weather": "暴風",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 482,
    "Since": 3.4,
    "Remark": ""
  },
  {
    "Fish": "ボサボサ",
    "Spot": "ウェストン・ウォーター",
    "Zone": "ドラヴァニア雲海",
    "From": "",
    "To": "",
    "Previous_Weather": "曇り",
    "Weather": "暴風",
    "Fish_Eyes": "有",
    "Intuition": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 498,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "ストームブラッドライダー",
    "Spot": "サルウーム・カシュ",
    "Zone": "ドラヴァニア雲海",
    "From": "",
    "To": "",
    "Previous_Weather": "快晴",
    "Weather": "暴風",
    "Fish_Eyes": "1m20s",
    "Intuition": "",
    "Bait": "ジャンボガガンボ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 499,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "ランデロプテルス",
    "Spot": "サルウーム・カシュ",
    "Zone": "ドラヴァニア雲海",
    "From": 5,
    "To": 8,
    "Previous_Weather": "",
    "Weather": "暴風",
    "Fish_Eyes": "",
    "Intuition": "スカイハイフィッシュx5",
    "Bait": "ジャンボガガンボ",
    "Mooch": "スカイハイフィッシュ",
    "Hookset": "ストロング",
    "Neko": 505,
    "Since": 3.5,
    "Remark": ""
  },
  {
    "Fish": "フックスティーラー",
    "Spot": "ミラージュクリーク上流",
    "Zone": "ラールガーズリーチ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "赤虫",
    "Mooch": "ギラバニアントラウト",
    "Hookset": "プレシジョン",
    "Neko": 760,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "シデンナマズ",
    "Spot": "ラールガーズリーチ",
    "Zone": "ラールガーズリーチ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "赤虫",
    "Mooch": "ギラバニアントラウト",
    "Hookset": "ストロング",
    "Neko": 808,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "レッドテイルゾンビー",
    "Spot": "星導山寺院入口",
    "Zone": "ラールガーズリーチ",
    "From": 8,
    "To": 12,
    "Previous_Weather": "",
    "Weather": "曇り",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ドバミミズ",
    "Mooch": "バルーンフロッグ",
    "Hookset": "ストロング",
    "Neko": 809,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "サーメットヘッド",
    "Spot": "ティモン川",
    "Zone": "ギラバニア辺境地帯",
    "From": 16,
    "To": 20,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 810,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "クセナカンサス",
    "Spot": "ティモン川",
    "Zone": "ギラバニア辺境地帯",
    "From": 16,
    "To": 20,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "サーメットヘッド",
    "Hookset": "ストロング",
    "Neko": 840,
    "Since": 4.5,
    "Remark": "ヌシ泳がせ"
  },
  {
    "Fish": "サファイアファン",
    "Spot": "夜の森",
    "Zone": "ギラバニア辺境地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 761,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "アークビショップフィッシュ",
    "Spot": "流星の尾",
    "Zone": "ギラバニア辺境地帯",
    "From": 12,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "雷・晴れ・快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 762,
    "Since": 4.3,
    "Remark": "晴れ・快晴・雷にホネトカシをトレードすると100%"
  },
  {
    "Fish": "タニクダリ",
    "Spot": "ベロジナ川",
    "Zone": "ギラバニア辺境地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "霧",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 811,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "コープスチャブ",
    "Spot": "ミラージュクリーク",
    "Zone": "ギラバニア辺境地帯",
    "From": 20,
    "To": 24,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 812,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "ヘモン",
    "Spot": "ブルズバス",
    "Zone": "ギラバニア山岳地帯",
    "From": 16,
    "To": 20,
    "Previous_Weather": "",
    "Weather": "曇り",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 814,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "ボンドスプリッター",
    "Spot": "夫婦池",
    "Zone": "ギラバニア山岳地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "砂塵",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 763,
    "Since": 4.3,
    "Remark": "ヌシ泳がせ"
  },
  {
    "Fish": "ドレパナスピス",
    "Spot": "夫婦池",
    "Zone": "ギラバニア山岳地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "砂塵",
    "Fish_Eyes": "",
    "Intuition": "ボンドスプリッターx2",
    "Bait": "サスペンドミノー",
    "Mooch": "ボンドスプリッター",
    "Hookset": "ストロング",
    "Neko": 841,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "ナガレクダリ",
    "Spot": "スロウウォッシュ",
    "Zone": "ギラバニア山岳地帯",
    "From": 8,
    "To": 12,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "赤虫",
    "Mooch": "ギラバニアントラウト",
    "Hookset": "ストロング",
    "Neko": 764,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "ラストティアー",
    "Spot": "ヒース滝",
    "Zone": "ギラバニア山岳地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "霧",
    "Weather": "晴れ",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "イクラ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 813,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "解脱魚",
    "Spot": "裁定者の像",
    "Zone": "ギラバニア山岳地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "曇り・霧・風・砂塵",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 815,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "アラミガンベール",
    "Spot": "アームズ・オブ・ミード",
    "Zone": "ギラバニア山岳地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "快晴",
    "Weather": "晴れ",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 822,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "ダイヤモンドアイ",
    "Spot": "ロッホ・セル湖",
    "Zone": "ギラバニア湖畔地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "快晴",
    "Fish_Eyes": "4m",
    "Intuition": "",
    "Bait": "蚕蛹",
    "Mooch": "ロックソルトフィッシュ",
    "Hookset": "ストロング",
    "Neko": 765,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "ステタカントゥス",
    "Spot": "ロッホ・セル湖",
    "Zone": "ギラバニア湖畔地帯",
    "From": 16,
    "To": 18,
    "Previous_Weather": "雷雨",
    "Weather": "",
    "Fish_Eyes": "有（スカルプター）",
    "Intuition": "スカルプターx2",
    "Bait": "蚕蛹",
    "Mooch": "ロックソルトフィッシュ",
    "Hookset": "ストロング",
    "Neko": 842,
    "Since": 4.5,
    "Remark": "気象条件はないが、スカルプターが雷しか釣れないため"
  },
  {
    "Fish": "ベジースキッパー",
    "Spot": "ネム・カール",
    "Zone": "アジムステップ",
    "From": 8,
    "To": 12,
    "Previous_Weather": "晴れ",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "赤虫",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 833,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "明けの旗魚",
    "Spot": "ハク・カール",
    "Zone": "アジムステップ",
    "From": 0,
    "To": 8,
    "Previous_Weather": "晴れ",
    "Weather": "霧",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ドバミミズ",
    "Mooch": "ザガス",
    "Hookset": "ストロング",
    "Neko": 834,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "ブレードスキッパー",
    "Spot": "ヤト・カール上流",
    "Zone": "アジムステップ",
    "From": 4,
    "To": 8,
    "Previous_Weather": "",
    "Weather": "霧",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 821,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "暮れの魚",
    "Spot": "アジム・カート",
    "Zone": "アジムステップ",
    "From": 8,
    "To": 16,
    "Previous_Weather": "雨・暴風",
    "Weather": "曇り",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ドバミミズ",
    "Mooch": "ザガス",
    "Hookset": "ストロング",
    "Neko": 820,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "シンタクヤブリ",
    "Spot": "タオ・カール",
    "Zone": "アジムステップ",
    "From": 20,
    "To": 24,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 772,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "ヤトカガン",
    "Spot": "ヤト・カール下流",
    "Zone": "アジムステップ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "風",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 773,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "ナーマの愛寵",
    "Spot": "ドタール・カー",
    "Zone": "アジムステップ",
    "From": 4,
    "To": 8,
    "Previous_Weather": "雨",
    "Weather": "晴れ・快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 832,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "神々の愛",
    "Spot": "ドタール・カー",
    "Zone": "アジムステップ",
    "From": 5,
    "To": 7,
    "Previous_Weather": "雨",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 845,
    "Since": 4.5,
    "Remark": "ナーマの恵みをトレードで１００％"
  },
  {
    "Fish": "バリマンボン",
    "Spot": "イサリ村沿岸",
    "Zone": "紅玉海",
    "From": 16,
    "To": 24,
    "Previous_Weather": "晴れ・快晴",
    "Weather": "雷",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "活海老",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 825,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "ウミダイジャ",
    "Spot": "オノコロ島近海",
    "Zone": "紅玉海",
    "From": "",
    "To": "",
    "Previous_Weather": "晴れ・快晴",
    "Weather": "風",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "活海老",
    "Mooch": "紅玉海老",
    "Hookset": "ストロング",
    "Neko": 818,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "春不知",
    "Spot": "沖之岩近海",
    "Zone": "紅玉海",
    "From": 16,
    "To": 20,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "アオイソメ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 768,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "ソクシツキ",
    "Spot": "ゼッキ島近海",
    "Zone": "紅玉海",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "活海老",
    "Mooch": "紅玉海老",
    "Hookset": "ストロング",
    "Neko": 769,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "菜食王",
    "Spot": "獄之蓋近海",
    "Zone": "紅玉海",
    "From": 20,
    "To": 24,
    "Previous_Weather": "",
    "Weather": "雷",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "活海老",
    "Mooch": "紅玉海老",
    "Hookset": "ストロング",
    "Neko": 823,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "ナナツボシ",
    "Spot": "ベッコウ島近海",
    "Zone": "紅玉海",
    "From": 10,
    "To": 18,
    "Previous_Weather": "雷",
    "Weather": "晴れ",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "アオイソメ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 824,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "クアル",
    "Spot": "紅玉台場近海",
    "Zone": "紅玉海",
    "From": 0,
    "To": 8,
    "Previous_Weather": "雷",
    "Weather": "曇り",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "アオイソメ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 817,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "紅龍",
    "Spot": "紅玉台場近海",
    "Zone": "紅玉海",
    "From": 4,
    "To": 8,
    "Previous_Weather": "雷",
    "Weather": "曇り",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "アオイソメ",
    "Mooch": "クアル",
    "Hookset": "ストロング",
    "Neko": 843,
    "Since": 4.5,
    "Remark": "紅蓮ラスボス"
  },
  {
    "Fish": "オニニラミ",
    "Spot": "アオサギ川",
    "Zone": "ヤンサ",
    "From": "",
    "To": "",
    "Previous_Weather": "晴れ",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 827,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "ザクロウミ",
    "Spot": "アオサギ池",
    "Zone": "ヤンサ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雨",
    "Fish_Eyes": "有",
    "Intuition": "",
    "Bait": "ドバミミズ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 826,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "仙寿の翁",
    "Spot": "ナマイ村溜池",
    "Zone": "ヤンサ",
    "From": 20,
    "To": 24,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 828,
    "Since": 4.5,
    "Remark": "トレード有効"
  },
  {
    "Fish": "七彩天主",
    "Spot": "七彩溝",
    "Zone": "ヤンサ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "藍彩魚x3(ET00-04) 橙彩魚x3(ET04~08) 緑彩魚x5(ET00-16)",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 844,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "ニジノヒトスジ",
    "Spot": "七彩渓谷",
    "Zone": "ヤンサ",
    "From": 12,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "霧",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 831,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "ボクデン",
    "Spot": "ドマ城前",
    "Zone": "ヤンサ",
    "From": 12,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 770,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "水天一碧",
    "Spot": "城下船場",
    "Zone": "ヤンサ",
    "From": 16,
    "To": 24,
    "Previous_Weather": "",
    "Weather": "暴雨",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 829,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "シャジクノミ",
    "Spot": "無二江東",
    "Zone": "ヤンサ",
    "From": 0,
    "To": 6,
    "Previous_Weather": "曇り",
    "Weather": "晴れ",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 830,
    "Since": 4.5,
    "Remark": ""
  },
  {
    "Fish": "羽衣美女",
    "Spot": "無二江西",
    "Zone": "ヤンサ",
    "From": "",
    "To": "",
    "Previous_Weather": "曇り",
    "Weather": "晴れ・快晴",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 819,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "羽衣鯉",
    "Spot": "梅泉郷",
    "Zone": "ヤンサ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "霧",
    "Fish_Eyes": "4m",
    "Intuition": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 771,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "ノボリリュウ",
    "Spot": "波止場全体",
    "Zone": "クガネ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "活海老",
    "Mooch": "紅玉海老",
    "Hookset": "",
    "Neko": 766,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "バクチウチ",
    "Spot": "シロガネ",
    "Zone": "シロガネ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "アオイソメ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 767,
    "Since": 4.3,
    "Remark": ""
  },
  {
    "Fish": "ヒメダカ",
    "Spot": "シロガネ水路",
    "Zone": "シロガネ",
    "From": 4,
    "To": 6,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ドバミミズ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 816,
    "Since": 4.4,
    "Remark": ""
  },
  {
    "Fish": "ゴールデンフィン",
    "Spot": "リムサ・ロミンサ：上甲板層",
    "Zone": "リムサ・ロミンサ",
    "From": 9,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ピルバグ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 208,
    "Since": 2.2,
    "Remark": ""
  },
  {
    "Fish": "メガオクトパス",
    "Spot": "リムサ・ロミンサ：下甲板層",
    "Zone": "リムサ・ロミンサ",
    "From": 9,
    "To": 17,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ラグワーム",
    "Mooch": "メルトールゴビー・ハーバーヘリング",
    "Hookset": "ストロング",
    "Neko": 230,
    "Since": 2.2,
    "Remark": ""
  },
  {
    "Fish": "ザルエラ",
    "Spot": "ゼファードリフト沿岸",
    "Zone": "中央ラノシア",
    "From": 9,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ラットの尾",
    "Mooch": "",
    "Hookset": "",
    "Neko": 201,
    "Since": 2.2,
    "Remark": ""
  },
  {
    "Fish": "ギガシャーク",
    "Spot": "サマーフォード沿岸",
    "Zone": "中央ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "快晴・晴れ",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ラグワーム",
    "Mooch": "メルトールゴビー・ハーバーヘリング・オーガバラクーダ",
    "Hookset": "ストロング",
    "Neko": 209,
    "Since": 2.2,
    "Remark": ""
  },
  {
    "Fish": "トリックスター",
    "Spot": "ローグ川",
    "Zone": "中央ラノシア",
    "From": 9,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "モスプパ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 202,
    "Since": 2.2,
    "Remark": ""
  },
  {
    "Fish": "スナガクレ",
    "Spot": "西アジェレス川",
    "Zone": "中央ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "ザリガニボール",
    "Mooch": "",
    "Hookset": "",
    "Neko": 211,
    "Since": 2.2,
    "Remark": ""
  },
  {
    "Fish": "ハイパーチ",
    "Spot": "ニーム川",
    "Zone": "中央ラノシア",
    "From": 4,
    "To": 8,
    "Previous_Weather": "",
    "Weather": "",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "シンキングミノー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 232,
    "Since": 2.2,
    "Remark": ""
  },
  {
    "Fish": "クリスタルパーチ",
    "Spot": "ささやきの谷",
    "Zone": "中央ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "霧・曇り・風",
    "Fish_Eyes": "",
    "Intuition": "",
    "Bait": "バターワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 205,
    "Since": 2.2,
    "Remark": ""
  }
]