osakanas = [
  {
    "Fish": "トラマフィッシュ",
    "Spot": "オークウッド",
    "Zone": "高地ラノシア",
    "From": 17,
    "To": 20,
    "Previous_Weather": "",
    "Weather": "曇り・霧",
    "Bait": "スピナーベイト",
    "Mooch": "スカルピン",
    "Hookset": "",
    "Neko": 241,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "スウィートニュート",
    "Spot": "ラベンダーベッド",
    "Zone": "ラベンダーベッド",
    "From": 23,
    "To": 4,
    "Previous_Weather": "",
    "Weather": "霧",
    "Bait": "コスリカ",
    "Mooch": "グラディエーターベタ",
    "Hookset": "",
    "Neko": 259,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ファットパース",
    "Spot": "リバーズミート",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 462,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ヘイルイーター",
    "Spot": "グレイテール滝",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "雪・吹雪",
    "Weather": "吹雪",
    "Bait": "ジャンボガンボボ",
    "Mooch": "グレイシャーコア",
    "Hookset": "プレシジョン",
    "Neko": 478,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "フレアフィッシュ",
    "Spot": "クルザス不凍池",
    "Zone": "クルザス西部高地",
    "From": 10,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "吹雪",
    "Bait": "ツチグモ",
    "Mooch": "ハルオネ",
    "Hookset": "ストロング",
    "Neko": 479,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ラ・レアル",
    "Spot": "アッシュプール",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 464,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "イエティキラー",
    "Spot": "ドラゴンスピット",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 463,
    "Since": 3.3,
    "Remark": "引っ掛け 50s+",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "氷の巫女",
    "Spot": "ベーンプール西",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "雪",
    "Weather": "吹雪",
    "Bait": "カディスラーヴァ",
    "Mooch": "ハルオネ",
    "Hookset": "ストロング",
    "Neko": 488,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "2m20s",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ネモ",
    "Spot": "ベーンプール南",
    "Zone": "クルザス西部高地",
    "From": "",
    "To": "",
    "Previous_Weather": "雪",
    "Weather": "吹雪",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 490,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ビショップフィッシュ",
    "Spot": "クリアプール",
    "Zone": "クルザス西部高地",
    "From": 10,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 489,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "3m",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シャリベネ",
    "Spot": "クリアプール",
    "Zone": "クルザス西部高地",
    "From": 0,
    "To": 3,
    "Previous_Weather": "",
    "Weather": "吹雪",
    "Bait": "ツチグモ",
    "Mooch": "ハルオネ",
    "Hookset": "プレシジョン",
    "Neko": 504,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "ハルオネx5",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "アクムノタネ",
    "Spot": "スモーキングウェイスト",
    "Zone": "高地ドラヴァニア",
    "From": 22,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "曇り・霧・砂塵",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 466,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "スケイルリッパー",
    "Spot": "悲嘆の飛泉",
    "Zone": "高地ドラヴァニア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "曇り・霧・砂塵",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 465,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "フォークタン",
    "Spot": "ウィロームリバー",
    "Zone": "高地ドラヴァニア",
    "From": 12,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 480,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "サンダースケイル",
    "Spot": "飽食の台地",
    "Zone": "高地ドラヴァニア",
    "From": 6,
    "To": 8,
    "Previous_Weather": "曇り・霧・砂塵",
    "Weather": "雷",
    "Bait": "ストーンラーヴァ",
    "Mooch": "マクロブラキウム",
    "Hookset": "ストロング",
    "Neko": 494,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "リドル",
    "Spot": "アネス・ソー",
    "Zone": "高地ドラヴァニア",
    "From": 8,
    "To": 16,
    "Previous_Weather": "快晴",
    "Weather": "快晴",
    "Bait": "マグマワーム",
    "Mooch": "グラナイトクラブ",
    "Hookset": "ストロング",
    "Neko": 495,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "5m",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "メテオトータス",
    "Spot": "モーン大岩窟",
    "Zone": "高地ドラヴァニア",
    "From": 8,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "マグマワーム",
    "Mooch": "グラナイトクラブ",
    "Hookset": "ストロング",
    "Neko": 467,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "聖竜の涙",
    "Spot": "モーン大岩窟西",
    "Zone": "高地ドラヴァニア",
    "From": 2,
    "To": 6,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "マグマワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 484,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "2m+ 2択ガチャ（2m→1mはハズレ）",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "溶岩帝王",
    "Spot": "光輪の祭壇",
    "Zone": "高地ドラヴァニア",
    "From": 8,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "マグマワーム",
    "Mooch": "グラナイトクラブ",
    "Hookset": "ストロング",
    "Neko": 496,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "5m (3択ガチャ)",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "プロブレマティカス",
    "Spot": "光輪の祭壇",
    "Zone": "高地ドラヴァニア",
    "From": 10,
    "To": 15,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "マグマワーム",
    "Mooch": "グラナイトクラブ",
    "Hookset": "ストロング",
    "Neko": 500,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "アロワナx3 カニx5",
    "Fish_Eyes": "3m (アロワナ)",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "水瓶王",
    "Spot": "サリャク河",
    "Zone": "低地ドラヴァニア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ブレーデッドジグ",
    "Mooch": "香魚",
    "Hookset": "ストロング",
    "Neko": 468,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "マダムバタフライ",
    "Spot": "クイックスピル・デルタ",
    "Zone": "低地ドラヴァニア",
    "From": 21,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Bait": "ストーンラーヴァ",
    "Mooch": "グリルダロパ",
    "Hookset": "ストロング",
    "Neko": 481,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "グリルダロパは弱震(8-11s)",
    "Load": "Yes"
  },
  {
    "Fish": "万能のゴブリバス",
    "Spot": "サリャク河中州",
    "Zone": "低地ドラヴァニア",
    "From": 2,
    "To": 6,
    "Previous_Weather": "雨",
    "Weather": "暴雨",
    "Bait": "ブレーデッドジグ",
    "Mooch": "香魚",
    "Hookset": "ストロング",
    "Neko": 487,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "スピーカー",
    "Spot": "サリャク河上流",
    "Zone": "低地ドラヴァニア",
    "From": "",
    "To": "",
    "Previous_Weather": "曇り・霧",
    "Weather": "暴雨",
    "Bait": "ツチグモ",
    "Mooch": "グリルダロパ",
    "Hookset": "ストロング",
    "Neko": 497,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "鎧魚",
    "Spot": "サリャク河上流",
    "Zone": "低地ドラヴァニア",
    "From": 1,
    "To": 4,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Bait": "ツチグモ",
    "Mooch": "グリルダロパ",
    "Hookset": "プレシジョン",
    "Neko": 502,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ハイアラガンクラブ改",
    "Spot": "アルファ管区",
    "Zone": "アジス・ラー",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "バイオレットワーム",
    "Mooch": "白金魚",
    "Hookset": "ストロング",
    "Neko": 473,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "魔科学物質666",
    "Spot": "廃液溜まり",
    "Zone": "アジス・ラー",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "バイオレットワーム",
    "Mooch": "白金魚",
    "Hookset": "プレシジョン",
    "Neko": 485,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "有",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "セティ",
    "Spot": "超星間交信塔",
    "Zone": "アジス・ラー",
    "From": 18,
    "To": 22,
    "Previous_Weather": "曇り",
    "Weather": "雷",
    "Bait": "バイオレットワーム",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 492,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "3m",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "バイオガピラルク",
    "Spot": "デルタ管区",
    "Zone": "アジス・ラー",
    "From": 21,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "曇り",
    "Bait": "ツチグモ",
    "Mooch": "エーテルアイ",
    "Hookset": "ストロング",
    "Neko": 474,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ハンドレッドアイ",
    "Spot": "パプスの大樹",
    "Zone": "アジス・ラー",
    "From": 6,
    "To": 10,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ツチグモ",
    "Mooch": "エーテルアイ",
    "Hookset": "プレシジョン",
    "Neko": 486,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "クリスタルピジョン",
    "Spot": "ハビスフィア",
    "Zone": "アジス・ラー",
    "From": "",
    "To": "",
    "Previous_Weather": "晴れ",
    "Weather": "雷",
    "Bait": "ジャンボガガンボ",
    "Mooch": "スカイハイフィッシュ",
    "Hookset": "ストロング",
    "Neko": 493,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "3m",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "アラガンブレード・シャーク",
    "Spot": "アジス・ラー旗艦島",
    "Zone": "アジス・ラー",
    "From": "",
    "To": "",
    "Previous_Weather": "曇り",
    "Weather": "雷",
    "Bait": "バイオレットワーム",
    "Mooch": "白金魚",
    "Hookset": "ストロング",
    "Neko": 477,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "オパビニア",
    "Spot": "アジス・ラー旗艦島",
    "Zone": "アジス・ラー",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷",
    "Bait": "バイオレットワーム",
    "Mooch": "白金魚",
    "Hookset": "プレシジョン",
    "Neko": 501,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "オプロプケンx3",
    "Fish_Eyes": "2m (オプロプケン)",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ザ・セカンドワン",
    "Spot": "ブルーウィンドウ",
    "Zone": "アバラシア雲海",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "風",
    "Bait": "ジャンボガガンボ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 472,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シーロストラタスモトロ",
    "Spot": "クラウドトップ",
    "Zone": "アバラシア雲海",
    "From": 10,
    "To": 13,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "ジャンボガガンボ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 483,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "クラウドバタフライ",
    "Spot": "モック・ウーグル島",
    "Zone": "アバラシア雲海",
    "From": 5,
    "To": 7,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Bait": "ジャンボガガンボ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 503,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "スカイフェアリー・セレネx３、スコーピオンフライx３",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "バスキングシャーク",
    "Spot": "モック・ウーグル島",
    "Zone": "アバラシア雲海",
    "From": "",
    "To": "",
    "Previous_Weather": "霧",
    "Weather": "快晴",
    "Bait": "レッドバルーン",
    "Mooch": "スカイフェアリー・セレネ",
    "Hookset": "ストロング",
    "Neko": 476,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "パイッサキラー",
    "Spot": "雲溜まり",
    "Zone": "アバラシア雲海",
    "From": 8,
    "To": 12,
    "Previous_Weather": "霧",
    "Weather": "快晴",
    "Bait": "ブレーデッドジグ",
    "Mooch": "ブルフロッグ",
    "Hookset": "ストロング",
    "Neko": 491,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "水墨魚",
    "Spot": "ヴール・シアンシラン",
    "Zone": "アバラシア雲海",
    "From": 14,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 471,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "有",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ラタトスクソウル",
    "Spot": "ランドロード遺構",
    "Zone": "ドラヴァニア雲海",
    "From": 4,
    "To": 6,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "ジャンボガガンボ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 470,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ヴィゾーヴニル",
    "Spot": "エイル・トーム",
    "Zone": "ドラヴァニア雲海",
    "From": 8,
    "To": 10,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 469,
    "Since": 3.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ディモルフォドン",
    "Spot": "ソーム・アル笠雲",
    "Zone": "ドラヴァニア雲海",
    "From": "",
    "To": "",
    "Previous_Weather": "快晴",
    "Weather": "暴風",
    "Bait": "ジャンボガガンボ",
    "Mooch": "スカイハイフィッシュ",
    "Hookset": "ストロング",
    "Neko": 475,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "モグルグポンポン",
    "Spot": "グリーンスウォード島",
    "Zone": "ドラヴァニア雲海",
    "From": 10,
    "To": 13,
    "Previous_Weather": "暴風",
    "Weather": "快晴",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 482,
    "Since": 3.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ボサボサ",
    "Spot": "ウェストン・ウォーター",
    "Zone": "ドラヴァニア雲海",
    "From": "",
    "To": "",
    "Previous_Weather": "曇り",
    "Weather": "暴風",
    "Bait": "ブルートリーチ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 498,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "有",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ストームブラッドライダー",
    "Spot": "サルウーム・カシュ",
    "Zone": "ドラヴァニア雲海",
    "From": "",
    "To": "",
    "Previous_Weather": "快晴",
    "Weather": "暴風",
    "Bait": "ジャンボガガンボ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 499,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "1m20s",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ランデロプテルス",
    "Spot": "サルウーム・カシュ",
    "Zone": "ドラヴァニア雲海",
    "From": 5,
    "To": 8,
    "Previous_Weather": "",
    "Weather": "暴風",
    "Bait": "ジャンボガガンボ",
    "Mooch": "スカイハイフィッシュ",
    "Hookset": "ストロング",
    "Neko": 505,
    "Since": 3.5,
    "Remark": "",
    "Intuition": "スカイハイフィッシュx5",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "フックスティーラー",
    "Spot": "ミラージュクリーク上流",
    "Zone": "ラールガーズリーチ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "赤虫",
    "Mooch": "ギラバニアントラウト",
    "Hookset": "プレシジョン",
    "Neko": 760,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シデンナマズ",
    "Spot": "ラールガーズリーチ",
    "Zone": "ラールガーズリーチ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷",
    "Bait": "赤虫",
    "Mooch": "ギラバニアントラウト",
    "Hookset": "ストロング",
    "Neko": 808,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "レッドテイルゾンビー",
    "Spot": "星導山寺院入口",
    "Zone": "ラールガーズリーチ",
    "From": 8,
    "To": 12,
    "Previous_Weather": "",
    "Weather": "曇り",
    "Bait": "ドバミミズ",
    "Mooch": "バルーンフロッグ",
    "Hookset": "ストロング",
    "Neko": 809,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "サーメットヘッド",
    "Spot": "ティモン川",
    "Zone": "ギラバニア辺境地帯",
    "From": 16,
    "To": 20,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 810,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "クセナカンサス",
    "Spot": "ティモン川",
    "Zone": "ギラバニア辺境地帯",
    "From": 16,
    "To": 20,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ザザムシ",
    "Mooch": "サーメットヘッド",
    "Hookset": "ストロング",
    "Neko": 840,
    "Since": 4.5,
    "Remark": "ヌシ泳がせ",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "サファイアファン",
    "Spot": "夜の森",
    "Zone": "ギラバニア辺境地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 761,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "アークビショップフィッシュ",
    "Spot": "流星の尾",
    "Zone": "ギラバニア辺境地帯",
    "From": 12,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "雷・晴れ・快晴",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 762,
    "Since": 4.3,
    "Remark": "晴れ・快晴・雷にホネトカシをトレードすると100%",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "タニクダリ",
    "Spot": "ベロジナ川",
    "Zone": "ギラバニア辺境地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "霧",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 811,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "コープスチャブ",
    "Spot": "ミラージュクリーク",
    "Zone": "ギラバニア辺境地帯",
    "From": 20,
    "To": 24,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 812,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ヘモン",
    "Spot": "ブルズバス",
    "Zone": "ギラバニア山岳地帯",
    "From": 16,
    "To": 20,
    "Previous_Weather": "",
    "Weather": "曇り",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 814,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ボンドスプリッター",
    "Spot": "夫婦池",
    "Zone": "ギラバニア山岳地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "砂塵",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 763,
    "Since": 4.3,
    "Remark": "ヌシ泳がせ",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ドレパナスピス",
    "Spot": "夫婦池",
    "Zone": "ギラバニア山岳地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "砂塵",
    "Bait": "サスペンドミノー",
    "Mooch": "ボンドスプリッター",
    "Hookset": "ストロング",
    "Neko": 841,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "ボンドスプリッターx2",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ナガレクダリ",
    "Spot": "スロウウォッシュ",
    "Zone": "ギラバニア山岳地帯",
    "From": 8,
    "To": 12,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "赤虫",
    "Mooch": "ギラバニアントラウト",
    "Hookset": "ストロング",
    "Neko": 764,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ラストティアー",
    "Spot": "ヒース滝",
    "Zone": "ギラバニア山岳地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "霧",
    "Weather": "晴れ",
    "Bait": "イクラ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 813,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "解脱魚",
    "Spot": "裁定者の像",
    "Zone": "ギラバニア山岳地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "曇り・霧・風・砂塵",
    "Weather": "快晴",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 815,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "アラミガンベール",
    "Spot": "アームズ・オブ・ミード",
    "Zone": "ギラバニア山岳地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "快晴",
    "Weather": "晴れ",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 822,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ダイヤモンドアイ",
    "Spot": "ロッホ・セル湖",
    "Zone": "ギラバニア湖畔地帯",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "快晴",
    "Bait": "蚕蛹",
    "Mooch": "ロックソルトフィッシュ",
    "Hookset": "ストロング",
    "Neko": 765,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "4m",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ステタカントゥス",
    "Spot": "ロッホ・セル湖",
    "Zone": "ギラバニア湖畔地帯",
    "From": 16,
    "To": 18,
    "Previous_Weather": "雷雨",
    "Weather": "",
    "Bait": "蚕蛹",
    "Mooch": "ロックソルトフィッシュ",
    "Hookset": "ストロング",
    "Neko": 842,
    "Since": 4.5,
    "Remark": "気象条件はないが、スカルプターが雷しか釣れないため",
    "Intuition": "スカルプターx2",
    "Fish_Eyes": "有（スカルプター）",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ベジースキッパー",
    "Spot": "ネム・カール",
    "Zone": "アジムステップ",
    "From": 8,
    "To": 12,
    "Previous_Weather": "晴れ",
    "Weather": "快晴",
    "Bait": "赤虫",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 833,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "明けの旗魚",
    "Spot": "ハク・カール",
    "Zone": "アジムステップ",
    "From": 0,
    "To": 8,
    "Previous_Weather": "晴れ",
    "Weather": "霧",
    "Bait": "ドバミミズ",
    "Mooch": "ザガス",
    "Hookset": "ストロング",
    "Neko": 834,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ブレードスキッパー",
    "Spot": "ヤト・カール上流",
    "Zone": "アジムステップ",
    "From": 4,
    "To": 8,
    "Previous_Weather": "",
    "Weather": "霧",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 821,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "暮れの魚",
    "Spot": "アジム・カート",
    "Zone": "アジムステップ",
    "From": 8,
    "To": 16,
    "Previous_Weather": "雨・暴風",
    "Weather": "曇り",
    "Bait": "ドバミミズ",
    "Mooch": "ザガス",
    "Hookset": "ストロング",
    "Neko": 820,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シンタクヤブリ",
    "Spot": "タオ・カール",
    "Zone": "アジムステップ",
    "From": 20,
    "To": 24,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 772,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ヤトカガン",
    "Spot": "ヤト・カール下流",
    "Zone": "アジムステップ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "風",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 773,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ナーマの愛寵",
    "Spot": "ドタール・カー",
    "Zone": "アジムステップ",
    "From": 4,
    "To": 8,
    "Previous_Weather": "雨",
    "Weather": "晴れ・快晴",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 832,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "神々の愛",
    "Spot": "ドタール・カー",
    "Zone": "アジムステップ",
    "From": 5,
    "To": 7,
    "Previous_Weather": "雨",
    "Weather": "快晴",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 845,
    "Since": 4.5,
    "Remark": "ナーマの恵みをトレードで１００％",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "バリマンボン",
    "Spot": "イサリ村沿岸",
    "Zone": "紅玉海",
    "From": 16,
    "To": 24,
    "Previous_Weather": "晴れ・快晴",
    "Weather": "雷",
    "Bait": "活海老",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 825,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ウミダイジャ",
    "Spot": "オノコロ島近海",
    "Zone": "紅玉海",
    "From": "",
    "To": "",
    "Previous_Weather": "晴れ・快晴",
    "Weather": "風",
    "Bait": "活海老",
    "Mooch": "紅玉海老",
    "Hookset": "ストロング",
    "Neko": 818,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "春不知",
    "Spot": "沖之岩近海",
    "Zone": "紅玉海",
    "From": 16,
    "To": 20,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "アオイソメ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 768,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ソクシツキ",
    "Spot": "ゼッキ島近海",
    "Zone": "紅玉海",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷",
    "Bait": "活海老",
    "Mooch": "紅玉海老",
    "Hookset": "ストロング",
    "Neko": 769,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "菜食王",
    "Spot": "獄之蓋近海",
    "Zone": "紅玉海",
    "From": 20,
    "To": 24,
    "Previous_Weather": "",
    "Weather": "雷",
    "Bait": "活海老",
    "Mooch": "紅玉海老",
    "Hookset": "ストロング",
    "Neko": 823,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ナナツボシ",
    "Spot": "ベッコウ島近海",
    "Zone": "紅玉海",
    "From": 10,
    "To": 18,
    "Previous_Weather": "雷",
    "Weather": "晴れ",
    "Bait": "アオイソメ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 824,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "クアル",
    "Spot": "紅玉台場近海",
    "Zone": "紅玉海",
    "From": 0,
    "To": 8,
    "Previous_Weather": "雷",
    "Weather": "曇り",
    "Bait": "アオイソメ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 817,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "紅龍",
    "Spot": "紅玉台場近海",
    "Zone": "紅玉海",
    "From": 4,
    "To": 8,
    "Previous_Weather": "雷",
    "Weather": "曇り",
    "Bait": "アオイソメ",
    "Mooch": "クアル",
    "Hookset": "ストロング",
    "Neko": 843,
    "Since": 4.5,
    "Remark": "紅蓮ラスボス",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "オニニラミ",
    "Spot": "アオサギ川",
    "Zone": "ヤンサ",
    "From": "",
    "To": "",
    "Previous_Weather": "晴れ",
    "Weather": "快晴",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 827,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ザクロウミ",
    "Spot": "アオサギ池",
    "Zone": "ヤンサ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雨",
    "Bait": "ドバミミズ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 826,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "有",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "仙寿の翁",
    "Spot": "ナマイ村溜池",
    "Zone": "ヤンサ",
    "From": 20,
    "To": 24,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 828,
    "Since": 4.5,
    "Remark": "トレード有効",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "七彩天主",
    "Spot": "七彩溝",
    "Zone": "ヤンサ",
    "From": "",
    "To": "",
    "Previous_Weather": "晴れ",
    "Weather": "晴れ・快晴",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 844,
    "Since": 4.5,
    "Remark": "緑彩魚が移ろい",
    "Intuition": "藍彩魚x3(ET00-04)　ザザムシ→紫彩魚泳がせ\n橙彩魚x3(ET04-08)　ザザムシ→赤彩魚泳がせ\n緑彩魚x5(ET00-16)　ザザムシ　移ろい",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ニジノヒトスジ",
    "Spot": "七彩渓谷",
    "Zone": "ヤンサ",
    "From": 12,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "霧",
    "Bait": "サスペンドミノー",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 831,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ボクデン",
    "Spot": "ドマ城前",
    "Zone": "ヤンサ",
    "From": 12,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 770,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "水天一碧",
    "Spot": "城下船場",
    "Zone": "ヤンサ",
    "From": 16,
    "To": 24,
    "Previous_Weather": "",
    "Weather": "暴雨",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 829,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シャジクノミ",
    "Spot": "無二江東",
    "Zone": "ヤンサ",
    "From": 0,
    "To": 6,
    "Previous_Weather": "曇り",
    "Weather": "晴れ",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "ストロング",
    "Neko": 830,
    "Since": 4.5,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "羽衣美女",
    "Spot": "無二江西",
    "Zone": "ヤンサ",
    "From": "",
    "To": "",
    "Previous_Weather": "曇り",
    "Weather": "晴れ・快晴",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 819,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "羽衣鯉",
    "Spot": "梅泉郷",
    "Zone": "ヤンサ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "霧",
    "Bait": "ザザムシ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 771,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "4m",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ノボリリュウ",
    "Spot": "波止場全体",
    "Zone": "クガネ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "活海老",
    "Mooch": "紅玉海老",
    "Hookset": "",
    "Neko": 766,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "バクチウチ",
    "Spot": "シロガネ",
    "Zone": "シロガネ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "アオイソメ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 767,
    "Since": 4.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ヒメダカ",
    "Spot": "シロガネ水路",
    "Zone": "シロガネ",
    "From": 4,
    "To": 6,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ドバミミズ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 816,
    "Since": 4.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ゴールデンフィン",
    "Spot": "リムサ・ロミンサ：上甲板層",
    "Zone": "リムサ・ロミンサ",
    "From": 9,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ピルバグ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 208,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "メガオクトパス",
    "Spot": "リムサ・ロミンサ：下甲板層",
    "Zone": "リムサ・ロミンサ",
    "From": 9,
    "To": 17,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ラグワーム",
    "Mooch": "メルトールゴビー・ハーバーヘリング",
    "Hookset": "ストロング",
    "Neko": 230,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ザルエラ",
    "Spot": "ゼファードリフト沿岸",
    "Zone": "中央ラノシア",
    "From": 9,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ラットの尾",
    "Mooch": "",
    "Hookset": "",
    "Neko": 201,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ギガシャーク",
    "Spot": "サマーフォード沿岸",
    "Zone": "中央ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "快晴・晴れ",
    "Bait": "ラグワーム",
    "Mooch": "メルトールゴビー・ハーバーヘリング・オーガバラクーダ",
    "Hookset": "ストロング",
    "Neko": 209,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "トリックスター",
    "Spot": "ローグ川",
    "Zone": "中央ラノシア",
    "From": 9,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "モスプパ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 202,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "スナガクレ",
    "Spot": "西アジェレス川",
    "Zone": "中央ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ザリガニボール",
    "Mooch": "",
    "Hookset": "",
    "Neko": 211,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ハイパーチ",
    "Spot": "ニーム川",
    "Zone": "中央ラノシア",
    "From": 4,
    "To": 8,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "シンキングミノー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 232,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "クリスタルパーチ",
    "Spot": "ささやきの谷",
    "Zone": "中央ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "霧・曇り・風",
    "Bait": "バターワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 205,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "オオゴエナマズ",
    "Spot": "モーニングウィドー",
    "Zone": "低地ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "モスプパ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 204,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "オシュオンプリント",
    "Spot": "モラビー湾西岸",
    "Zone": "低地ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ゴビーボール",
    "Mooch": "",
    "Hookset": "",
    "Neko": 203,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シルドラ",
    "Spot": "シダーウッド沿岸部",
    "Zone": "低地ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雨",
    "Bait": "スプーンワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 233,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ザ・リッパー",
    "Spot": "モラビー造船廠",
    "Zone": "低地ラノシア",
    "From": 21,
    "To": 3,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ゴビーボール",
    "Mooch": "",
    "Hookset": "",
    "Neko": 235,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シルバーソブリン",
    "Spot": "オシュオン灯台",
    "Zone": "低地ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "弓角",
    "Mooch": "",
    "Hookset": "",
    "Neko": 213,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "メテオサバイバー",
    "Spot": "ソルトストランド",
    "Zone": "低地ラノシア",
    "From": 3,
    "To": 5,
    "Previous_Weather": "",
    "Weather": "霧・曇り・風",
    "Bait": "ラットの尾",
    "Mooch": "",
    "Hookset": "",
    "Neko": 239,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "サーベルタイガーコッド",
    "Spot": "キャンドルキープ埠頭",
    "Zone": "低地ラノシア",
    "From": 16,
    "To": 22,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ゴビーボール",
    "Mooch": "",
    "Hookset": "",
    "Neko": 214,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "フェアリークイーン",
    "Spot": "エンプティハート",
    "Zone": "低地ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "霧・曇り・風",
    "Bait": "スピナーベイト",
    "Mooch": "",
    "Hookset": "",
    "Neko": 220,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "オヤジウオ",
    "Spot": "ブラインドアイアン坑道",
    "Zone": "低地ラノシア",
    "From": 17,
    "To": 19,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ハナアブ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 238,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ビアナックブーン",
    "Spot": "南ブラッドショア",
    "Zone": "東ラノシア",
    "From": 20,
    "To": 23,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "シュリンプフィーダー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 245,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シャークトゥーナ",
    "Spot": "コスタ・デル・ソル",
    "Zone": "東ラノシア",
    "From": 19,
    "To": 21,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "スプーンワーム",
    "Mooch": "フルムーンサーディン",
    "Hookset": "ストロング",
    "Neko": 251,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ボンバードフィッシュ",
    "Spot": "北ブラッドショア",
    "Zone": "東ラノシア",
    "From": 9,
    "To": 15,
    "Previous_Weather": "",
    "Weather": "快晴",
    "Bait": "へリングボール",
    "Mooch": "",
    "Hookset": "",
    "Neko": 260,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ソルター",
    "Spot": "隠れ滝",
    "Zone": "東ラノシア",
    "From": 17,
    "To": 19,
    "Previous_Weather": "",
    "Weather": "快晴・晴れ",
    "Bait": "ハニーワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 261,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ドラウンドスナイパー",
    "Spot": "東アジェレス川",
    "Zone": "東ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "快晴・晴れ",
    "Bait": "スナーブルフライ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 274,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "テレプシコレアン",
    "Spot": "レインキャッチャー樹林",
    "Zone": "東ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "霧",
    "Bait": "ハニーワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 275,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ミラースケイル",
    "Spot": "レインキャッチャー沼沢地",
    "Zone": "東ラノシア",
    "From": 9,
    "To": 16,
    "Previous_Weather": "",
    "Weather": "快晴・晴れ",
    "Bait": "バターワーム",
    "Mooch": "銅魚",
    "Hookset": "プレシジョン",
    "Neko": 276,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "黄金魚",
    "Spot": "レッドマンティス滝",
    "Zone": "東ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ハニーワーム",
    "Mooch": "銀魚",
    "Hookset": "ストロング",
    "Neko": 288,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "オールドマーリン",
    "Spot": "ロータノ海沖合：船首",
    "Zone": "東ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "雨・暴雨",
    "Weather": "快晴",
    "Bait": "ピルバグ",
    "Mooch": "ハーバーヘリング→オーガバラクーダ",
    "Hookset": "ストロング",
    "Neko": 289,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ネプトの竜",
    "Spot": "ロータノ海沖合：船尾",
    "Zone": "東ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雨・暴雨",
    "Bait": "ポーラークリル",
    "Mooch": "",
    "Hookset": "",
    "Neko": 290,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "リトルサラオスx3",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "スケーリーフット",
    "Spot": "スウィフトパーチ入植地",
    "Zone": "西ラノシア",
    "From": 19,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ポーラークリル",
    "Mooch": "",
    "Hookset": "プレシジョン",
    "Neko": 210,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ジャンクモンガー",
    "Spot": "スカルバレー沿岸部",
    "Zone": "西ラノシア",
    "From": 16,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ラグワーム",
    "Mooch": "メルトールゴビー・ワフー",
    "Hookset": "",
    "Neko": 207,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ローンリッパー",
    "Spot": "ハーフストーン沿岸部",
    "Zone": "西ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "暴風",
    "Bait": "ヘヴィメタルジグ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 262,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ヘルムズマンズハンド",
    "Spot": "幻影諸島北岸",
    "Zone": "西ラノシア",
    "From": 9,
    "To": 15,
    "Previous_Weather": "",
    "Weather": "霧・曇り・風",
    "Bait": "ピルバグ",
    "Mooch": "オーシャンクラウド",
    "Hookset": "",
    "Neko": 277,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "コエラカントゥス",
    "Spot": "幻影諸島南岸",
    "Zone": "西ラノシア",
    "From": 22,
    "To": 3,
    "Previous_Weather": "",
    "Weather": "霧・曇り・風",
    "Bait": "スプーンワーム",
    "Mooch": "フルムーンサーディン",
    "Hookset": "",
    "Neko": 291,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "エンドセラス",
    "Spot": "幻影諸島南岸",
    "Zone": "西ラノシア",
    "From": 20,
    "To": 4,
    "Previous_Weather": "晴れ・快晴",
    "Weather": "霧・曇り・風",
    "Bait": "スプーンワーム",
    "Mooch": "フルムーンサーディン",
    "Hookset": "",
    "Neko": 292,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "リムレーンズソード",
    "Spot": "ブルワーズ灯台",
    "Zone": "西ラノシア",
    "From": 9,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "快晴・晴れ",
    "Bait": "弓角",
    "Mooch": "",
    "Hookset": "",
    "Neko": 216,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ラブカ",
    "Spot": "船の墓場",
    "Zone": "西ラノシア",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "霧・曇り・風",
    "Bait": "ラグワーム",
    "Mooch": "メルトールゴビー→ワフー→ジャイアントスキッド",
    "Hookset": "",
    "Neko": 286,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "キャプテンズチャリス",
    "Spot": "サプサ産卵地",
    "Zone": "西ラノシア",
    "From": 23,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "スプーンワーム",
    "Mooch": "フルムーンサーディン",
    "Hookset": "",
    "Neko": 284,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シーハッグ",
    "Spot": "船隠しの港",
    "Zone": "西ラノシア",
    "From": 19,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "快晴・晴れ",
    "Bait": "ラグワーム",
    "Mooch": "メルトールゴビー→ワフー",
    "Hookset": "",
    "Neko": 293,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ジャンヌ・トラウト",
    "Spot": "愚か者の滝",
    "Zone": "高地ラノシア",
    "From": 4,
    "To": 6,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "クロウフライ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 240,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "スプリングキング",
    "Spot": "ブロンズレイク北東岸",
    "Zone": "高地ラノシア",
    "From": 16,
    "To": 19,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "スピナーベイト",
    "Mooch": "",
    "Hookset": "",
    "Neko": 263,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ワーム・オブ・ニーム",
    "Spot": "ブロンズレイク・シャロー",
    "Zone": "高地ラノシア",
    "From": 19,
    "To": 22,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "バターワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 252,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "サンダーガット",
    "Spot": "ロングクライム渓谷",
    "Zone": "外地ラノシア",
    "From": 19,
    "To": 3,
    "Previous_Weather": "",
    "Weather": "雨",
    "Bait": "テッポウムシ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 273,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "トゥイッチビアード",
    "Spot": "ミスト・ヴィレッジ",
    "Zone": "ミスト・ヴィレッジ",
    "From": 4,
    "To": 6,
    "Previous_Weather": "",
    "Weather": "快晴・晴れ",
    "Bait": "スプーンワーム",
    "Mooch": "フルムーンサーディン",
    "Hookset": "",
    "Neko": 253,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "招嵐王",
    "Spot": "グリダニア：翡翠湖畔",
    "Zone": "グリダニア：新市街",
    "From": 17,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "雨",
    "Bait": "テッポウムシ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 236,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ブラッディブルワー",
    "Spot": "グリダニア：紅茶川水系下流",
    "Zone": "グリダニア：新市街",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ザリガニボール",
    "Mooch": "",
    "Hookset": "",
    "Neko": 219,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "マトロンカープ",
    "Spot": "グリダニア：囁きの渓谷",
    "Zone": "グリダニア：旧市街",
    "From": 15,
    "To": 21,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ブラッドワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 231,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "意地ブナ",
    "Spot": "グリダニア：紅茶川水系上流",
    "Zone": "グリダニア：旧市街",
    "From": 9,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "霧・曇り",
    "Bait": "クロウフライ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 224,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "カイラージョン",
    "Spot": "葉脈水系",
    "Zone": "黒衣森：中央森林",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "モスプパ",
    "Mooch": "ゼブラゴビー",
    "Hookset": "ストロング",
    "Neko": 228,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "人面魚",
    "Spot": "鏡池",
    "Zone": "黒衣森：中央森林",
    "From": 21,
    "To": 3,
    "Previous_Weather": "",
    "Weather": "雨",
    "Bait": "バターワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 223,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "レヴィンライト",
    "Spot": "エバーシェイド",
    "Zone": "黒衣森：中央森林",
    "From": 18,
    "To": 23,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ハナアブ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 256,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "グリーンジェスター",
    "Spot": "芽吹きの池",
    "Zone": "黒衣森：中央森林",
    "From": 18,
    "To": 21,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ハニーワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 270,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ブラッドバス",
    "Spot": "ハウケタ御用邸",
    "Zone": "黒衣森：中央森林",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷",
    "Bait": "ハニーワーム",
    "Mooch": "銀魚",
    "Hookset": "",
    "Neko": 271,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ダークアンブッシャー",
    "Spot": "花蜜桟橋",
    "Zone": "黒衣森：東部森林",
    "From": 21,
    "To": 3,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "モスプパ",
    "Mooch": "ゼブラゴビー",
    "Hookset": "プレシジョン",
    "Neko": 217,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シルフズベーン",
    "Spot": "青翠の奈落",
    "Zone": "黒衣森：東部森林",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雨",
    "Bait": "バターワーム",
    "Mooch": "銅魚",
    "Hookset": "",
    "Neko": 248,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "モルバ",
    "Spot": "さざなみ小川",
    "Zone": "黒衣森：東部森林",
    "From": 18,
    "To": 2,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ユスリカ",
    "Mooch": "グラディエーターペタ",
    "Hookset": "プレシジョン",
    "Neko": 206,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "マジック・マッシュルームクラブ",
    "Spot": "シルフランド渓谷",
    "Zone": "黒衣森：東部森林",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "曇り・霧",
    "Bait": "スピナーベイト",
    "Mooch": "スカルピン",
    "Hookset": "プレシジョン",
    "Neko": 309,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ターミネーター",
    "Spot": "十二神大聖堂",
    "Zone": "黒衣森：東部森林",
    "From": 21,
    "To": 23,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "バターワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 243,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ビッグバイパー",
    "Spot": "ハズーバ支流：上流",
    "Zone": "黒衣森：南部森林",
    "From": 18,
    "To": 19,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "バターワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 244,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シンカー",
    "Spot": "ハズーバ支流：中流",
    "Zone": "黒衣森：南部森林",
    "From": 21,
    "To": 3,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "シンキングミノー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 257,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "フローティングボルダー",
    "Spot": "ハズーバ支流：下流",
    "Zone": "黒衣森：南部森林",
    "From": 0,
    "To": 8,
    "Previous_Weather": "",
    "Weather": "曇り・霧",
    "Bait": "バスボール",
    "Mooch": "",
    "Hookset": "",
    "Neko": 249,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "グリナー",
    "Spot": "ハズーバ支流：東",
    "Zone": "黒衣森：南部森林",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ハナアブ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 250,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ゴブスレイヤー",
    "Spot": "ゴブリン族の生簀",
    "Zone": "黒衣森：南部森林",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷・雷雨",
    "Bait": "ハニーワーム",
    "Mooch": "銀魚",
    "Hookset": "",
    "Neko": 258,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "雷皇子",
    "Spot": "根渡り沼",
    "Zone": "黒衣森：南部森林",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷雨",
    "Bait": "ガディスラーヴァ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 272,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "オオタキタロ",
    "Spot": "ウルズの恵み",
    "Zone": "黒衣森：南部森林",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷・雷雨",
    "Bait": "グロウワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 310,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ナミタロ",
    "Spot": "ウルズの恵み",
    "Zone": "黒衣森：南部森林",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "雷・雷雨",
    "Bait": "トップウォーターフロッグ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 311,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "オオタキタロ",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ブルーウィドー",
    "Spot": "さざめき川",
    "Zone": "黒衣森：北部森林",
    "From": 9,
    "To": 14,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "フローティングミノー",
    "Mooch": "",
    "Hookset": "",
    "Neko": 222,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ジャッジレイ",
    "Spot": "フォールゴウド秋瓜湖畔",
    "Zone": "黒衣森：北部森林",
    "From": 17,
    "To": 21,
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "フェザントフライ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 218,
    "Since": 2.2,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "シャドーストリーク",
    "Spot": "プラウドクリーク",
    "Zone": "黒衣森：北部森林",
    "From": 4,
    "To": 10,
    "Previous_Weather": "",
    "Weather": "霧",
    "Bait": "トップウォーターフロッグ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 283,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "コーネリア",
    "Spot": "タホトトル湖畔",
    "Zone": "黒衣森：北部森林",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "レインボースプーン",
    "Mooch": "",
    "Hookset": "",
    "Neko": 296,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ダナフェンズマーク",
    "Spot": "クルザス川",
    "Zone": "クルザス中央高地",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "吹雪",
    "Bait": "フェザントフライ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 268,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "マハール",
    "Spot": "ウィッチドロップ",
    "Zone": "クルザス中央高地",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "吹雪",
    "Bait": "ホバーワーム",
    "Mooch": "スプリットクラウド",
    "Hookset": "ストロング",
    "Neko": 307,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ショニサウルス",
    "Spot": "ウィッチドロップ",
    "Zone": "クルザス中央高地",
    "From": "",
    "To": "",
    "Previous_Weather": "晴れ・快晴",
    "Weather": "吹雪",
    "Bait": "ホバーワーム",
    "Mooch": "マハール",
    "Hookset": "ストロング",
    "Neko": 308,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "スターブライト",
    "Spot": "剣ヶ峰山麓",
    "Zone": "クルザス中央高地",
    "From": 20,
    "To": 4,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "ツチグモ",
    "Mooch": "アバラシアスメルト",
    "Hookset": "ストロング",
    "Neko": 281,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ダークスター",
    "Spot": "聖ダナフェンの落涙",
    "Zone": "クルザス中央高地",
    "From": 19,
    "To": 4,
    "Previous_Weather": "",
    "Weather": "雪・吹雪",
    "Bait": "ツチグモ",
    "Mooch": "アバラシアスメルト",
    "Hookset": "ストロング",
    "Neko": 305,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ドーンメイデン",
    "Spot": "キャンプ・ドラゴンヘッド溜池",
    "Zone": "クルザス中央高地",
    "From": 5,
    "To": 7,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "フェザントフライ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 280,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "カローンズランタン",
    "Spot": "聖ダナフェンの旅程",
    "Zone": "クルザス中央高地",
    "From": 0,
    "To": 4,
    "Previous_Weather": "",
    "Weather": "雪・吹雪",
    "Bait": "グロウワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 269,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "メイトリアーク",
    "Spot": "調査隊の氷穴",
    "Zone": "クルザス中央高地",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "",
    "Bait": "ツチグモ",
    "Mooch": "アバラシアスメルト",
    "Hookset": "プレシジョン",
    "Neko": 282,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ブルーコープス",
    "Spot": "スノークローク大氷壁",
    "Zone": "クルザス中央高地",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "ガディスラーヴァ",
    "Mooch": "",
    "Hookset": "",
    "Neko": 306,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "アノマロカリス",
    "Spot": "イシュガルド大雲海",
    "Zone": "クルザス中央高地",
    "From": 10,
    "To": 15,
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "ホバーワーム",
    "Mooch": "スプリットクラウド",
    "Hookset": "ストロング",
    "Neko": 285,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "エーテルラウス",
    "Spot": "銀泪湖北岸",
    "Zone": "モードゥナ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "妖霧",
    "Bait": "グロウワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 287,
    "Since": 2.3,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ヴォイドバス",
    "Spot": "早霜峠",
    "Zone": "モードゥナ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "妖霧",
    "Bait": "グロウワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 295,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ニンジャベタ",
    "Spot": "タングル湿林",
    "Zone": "モードゥナ",
    "From": 18,
    "To": 9,
    "Previous_Weather": "",
    "Weather": "妖霧",
    "Bait": "ユスリカ",
    "Mooch": "グラディエーターベタ→アサシンベタ",
    "Hookset": "ストロング",
    "Neko": 297,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "インフェルノホーン",
    "Spot": "タングル湿林源流",
    "Zone": "モードゥナ",
    "From": "",
    "To": "",
    "Previous_Weather": "",
    "Weather": "晴れ・快晴",
    "Bait": "グロウワーム",
    "Mooch": "",
    "Hookset": "",
    "Neko": 294,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "血紅龍",
    "Spot": "唄う裂谷",
    "Zone": "モードゥナ",
    "From": 4,
    "To": 12,
    "Previous_Weather": "晴れ",
    "Weather": "霧",
    "Bait": "ハニーワーム",
    "Mooch": "銀魚",
    "Hookset": "ストロング",
    "Neko": 312,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "ジャノ",
    "Spot": "唄う裂谷北部",
    "Zone": "モードゥナ",
    "From": 8,
    "To": 18,
    "Previous_Weather": "",
    "Weather": "妖霧",
    "Bait": "ハニーワーム",
    "Mooch": "銀魚→金魚",
    "Hookset": "ストロング",
    "Neko": 298,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  },
  {
    "Fish": "クノ・ザ・キラー",
    "Spot": "唄う裂谷北部",
    "Zone": "モードゥナ",
    "From": 8,
    "To": 22,
    "Previous_Weather": "",
    "Weather": "妖霧",
    "Bait": "ハニーワーム",
    "Mooch": "銀魚→アサシンベタ",
    "Hookset": "ストロング",
    "Neko": 299,
    "Since": 2.4,
    "Remark": "",
    "Intuition": "",
    "Fish_Eyes": "",
    "Advice": "",
    "Load": "Yes"
  }
]